apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: rshiny-server
metadata:
  annotations:
    description: Build and run R Shiny Server Applications
    iconClass: icon-ruby
    openshift.io/display-name: R Shiny Server
    tags: builder,r,shiny,unc
  creationTimestamp: null
  name: rshiny-server
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
      app-route: ${NAME}
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    labels:
      app: ${NAME}
    name: ${NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: shinyserver:latest
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    labels:
      app: ${NAME}
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - image: ' '
          livenessProbe:
            initialDelaySeconds: 180
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          name: ${NAME}
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the frontend objects defined in this template. Must be all lowercase, and consist of only letters, numbers, dashes (but not at the end).
  displayName: Name
  name: NAME
  required: true
  value: shiny-server
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/rstudio/shiny-examples.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference/Branch
  name: SOURCE_REPOSITORY_REF
  required: true
  value: master
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: CONTEXT_DIR
  value: /
- description: The exposed hostname that will route to the application, if left blank
    a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: 'NOTE: Advanced users only. GitHub trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.'
  displayName: "GitHub Webhook Secret"
  name: GITHUB_WEBHOOK_SECRET
  generate: expression
  from: '[a-zA-Z0-9]{40}'
- description: 'NOTE: Advanced users only. Generic trigger secret, for use with GitLab and others.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.'
  displayName: "Generic Webhook Secret"
  name: GENERIC_WEBHOOK_SECRET
  generate: expression
  from: '[a-zA-Z0-9]{16}'
